name: test_deploiement
run-name: docker-build

on: 
  push:
    branches: dev

jobs:
  test-runner:
    runs-on: test-backend

    steps:
      - name: Checkout
        uses: app-test-deploiement-cicd/backend/test/info.services.test.js
      - run: npm test
