name: test_deploiement
run-name: docker-build

on:
  push:
    branches:
      - dev

jobs:
  test-runner:
    runs-on: test-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installation des dépendances
        working-directory: ./backend
        run: npm install

      - name: Lancement des tests
        working-directory: ./backend
        run: npm test